"""empty message

Revision ID: 5acf7c319b25
Revises: be175d6eb22d
Create Date: 2024-10-03 22:52:58.989075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acf7c319b25'
down_revision = 'be175d6eb22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'eventid')
    )
    op.create_table('clubs',
    sa.Column('clubid', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.Text(), nullable=False),
    sa.Column('fa1', sa.Integer(), nullable=False),
    sa.Column('fa2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('clubid'),
    sa.UniqueConstraint('club_name')
    )
    op.create_table('events',
    sa.Column('eventid', sa.Integer(), nullable=False),
    sa.Column('eventname', sa.Text(), nullable=False),
    sa.Column('clubid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('max_volunteers', sa.Integer(), nullable=False),
    sa.Column('current_volunteers', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('eventid'),
    sa.UniqueConstraint('eventname')
    )
    op.create_table('user_details',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('clubid', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'clubid'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credentials', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('user_details')
    op.drop_table('events')
    op.drop_table('clubs')
    op.drop_table('attendance')
    # ### end Alembic commands ###
